apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: blackjack-api
  template:
    metadata:
      labels:
        component: blackjack-api
    spec:
      containers:
        - name: api
          image: ghcr.io/nikodemwrona/nest-next-blackjack-game/blackjack-api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4000"
            - name: PICKATALE_API_URL
              value: "https://pickatale-backend-case.herokuapp.com/shuffle"
          ports:
            - containerPort: 4000